# pyproject.toml
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "safestore"
# Bump version for Phase 2 features
version = "1.1.0" # <-- BUMPED VERSION
description = "SQLite-based vector database utility optimized for LLM RAG integration."
readme = "README.md"
requires-python = ">=3.8"
license = { file = "LICENSE" } # Add a LICENSE file (e.g., Apache 2.0)
authors = [
    { name = "ParisNeo", email = "parisneo_ai@gmail.com" },
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12", # Added 3.12
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Topic :: Database",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]
dependencies = [
    "numpy>=1.21",
    "ascii_colors>=0.7.0",
    "filelock>=3.8", # For future concurrency
]

[project.optional-dependencies]
parsing = [] # Will add PDF/DOCX libs later
sentence-transformers = ["sentence-transformers>=2.2.0"]
tfidf = ["scikit-learn>=1.0"] # Added scikit-learn dependency
# Add other vectorizer deps later:
# openai = ["openai>=1.0"]
# ollama = ["ollama"]

# Convenience extra to install all vectorizers currently supported
all-vectorizers = [
    "safestore[sentence-transformers]",
    "safestore[tfidf]",
]
all = ["safestore[all-vectorizers]", "safestore[parsing]"] # Future combined extra

[project.urls]
Homepage = "https://github.com/ParisNeo/safestore"
Repository = "https://github.com/ParisNeo/safestore" # Updated repo URL assumption

# Optional: Configure tools like black, ruff via pyproject.toml
# [tool.black]
# line-length = 88
#
# [tool.ruff]
# select = ["E", "F", "W", "I", "UP", "PL", "T20"] # Example selections
# ignore = []
# line-length = 88